default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev:  v3.15.2
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus", "--keep-runtime-typing"]
        stages: [ commit ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
    -   id: ruff
        args: ["--fix"]
        stages: [ commit ]

-   repo: https://github.com/korawica/clishelf
    rev: v0.2.4
    hooks:
    -   id: shelf-commit-msg
