name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    environment:
      name: gh-image
      url: https://github.com/ddeutils/ddeapp-flask/pkgs/container/dfa-flask
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . --tag ${{ vars.GH_REPO_URL }}:latest
          docker push ${{ vars.GH_REPO_URL }}:latest

      - name: Test Running Docker image
        run: |
          docker pull ${{ vars.GH_REPO_URL }}:latest
          docker run -d \
            --name dfa-flask-local \
            -p 5000:5000 \
            ${{ vars.GH_REPO_URL }}:latest
          docker ps -a
