name: publish
on:
  push:
    branches: [main]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the dfa-flask-postgres Docker image
        run: |
          docker build . --tag ghcr.io/korawica/dfa-flask-postgres:latest
          docker push ghcr.io/korawica/dfa-flask-postgres:latest

      - name: Test Running the dfa-flask-postgres Docker image
        run: |
          docker pull ghcr.io/korawica/dfa-flask-postgres:latest
          docker run -d \
            --name dfa-flask-postgres-local \
            -p 5000:5000 \
            ghcr.io/korawica/dfa-flask-postgres:latest
          docker ps -a
