name: test

on:
  push:
    branches:
      - "main"
      - "*.*.*"
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

permissions:
  contents: read
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.9"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.analytic.txt') }}-test

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -U pip
          pip install -r requirements.analytic.txt
          pip install -r requirements.txt
          pip install pytest

      - name: Check git is working
        run: |
          git config --global user.email "ddeutils@github.actions"
          git config --global user.name "Testing Git on Travis CI"
          git --version
          git config --list

      - name: Test with pytest
        run: |
          pytest -v
